name: JessicaMeadows
favicon: null
layout_spectrum: 0.90243
typography_spectrum: 0.55906
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000002'
    - '#898680'
    - '#6a625c'
    - '#adb5b3'
    - '#e3e6ea'
  brandStrength: 0.8125
  lightness: 0.4375
  saturation: 0.4375
  rhythmicContrast: 0.5544962987769395
purpose: []
